project:
  type: website

website:
  title: "Effective Snakemake on Computer Clusters"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Snakemake Basics
        menu: 
          - quarto/About-Snakemake.qmd
          - quarto/Snakemake-Essentials.qmd
      - text: More Snakemake
        menu: 
          - quarto/Elaborating-rules.qmd
          - quarto/Config-files.qmd
      - text: Cluster Integration
        menu:
          - quarto/Cluster-friendly-Snakemake.qmd
      - text: Applications
        menu: 
          - quarto/Qiime2-Applications.qmd
          - quarto/Using-R-with-Snakemake.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

