project:
  type: website

website:
  title: "Effective-Snakemake-HPC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - About-Snakemake.qmd
      - Snakemake-Essentials.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

