project:
  type: website

website:
  title: "Effective Snakemake on Computer Clusters"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - quarto/About-Snakemake.qmd
      - quarto/Snakemake-Essentials.qmd
      - quarto/Elaborating-rules.qmd
      - quarto/Cluster-friendly-Snakemake.qmd
      - quarto/Qiime2-Applications.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

