project:
  type: website

website:
  title: "Effective Snakemake on Computer Clusters"
  navbar:
    left:
      - href: quarto/index.qmd
        text: Home
      - quarto/About-Snakemake.qmd
      - quarto/Snakemake-Essentials.qmd
      - quarto/Cluster-friendly-Snakemake.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

