---
title: "Qiime2 Applications"
---

# Getting Qiime2 and Snakemake to work together 
Firstly, let's make sure that you have `conda`, `mamba-forge`, and Qiime2 installed. Follow the installation instructions for the operating system of your local computer (or wherever you want to install Qiime2) which can be found [here](https://docs.qiime2.org/2023.5/install/native/).

Once you have Qiime2 installed, activate your Qiime2 environment by running `conda activate qiime2-2023.5` before running:

```
pip install snakemake
```

You now have Snakemake installed in your Qiime2 environment and can start working on your pipeline!

# Example workflow
```snakemake
rule all:
    input:
        "test_seqs.fasta",
        "databases/sepp-refs-silva-128.qza",
        "databases/silva-138-99-515-806-nb-classifier.qza",
        "merged_table.qza"


rule convert_to_fasta:
    input:
        "test_seqs.qza"
    output:
        "test_seqs.fasta"
    conda:
        # you need to reference your installed Qiime2 environment
        # or you can activate that environment before calling snakemake 
        # and you don't have to reference it here 
        "qiime2-2023.5"
    shell:
        """
        qiime tools export \
            --input-path {input} \
            --output-path ./ # this puts the output file in your current working directory
        
        mv dna-sequences.fasta {output}
        """ 

# you can reference online classifiers via wget 
# so you don't need to have them downloaded already
rule get_reference_databases:
    output:
        "databases/sepp-refs-silva-128.qza",
        "databases/silva-138-99-515-806-nb-classifier.qza"
    shell:
        """
        wget https://data.qiime2.org/2023.5/common/sepp-refs-silva-128.qza -P ./databases/
        wget https://data.qiime2.org/2023.5/common/silva-138-99-515-806-nb-classifier.qza -P ./databases/
        """

rule merge_tables:
    input:
        table1="table1.qza",
        table2="table2.qza"
    output:
        merged_table="merged_table.qza"
    conda:
        "qiime2-2023.5"
    shell:
        """
        qiime feature-table merge \
            --i-tables {input.table1} \
            --i-tables {input.table2} \
            --o-merged-table {output.merged_table}
        """
```

# Oh no! Someone is unhappy, what do I do?
Both Qiime2 and Snakemake are notoriously known for being picky about the little things (i.e. did you have an extra space that you forgot about after one of your commands and now you have a really unhelpful error message?) and sometimes the combination of the two can be incredibly frustrating.

## Things I've had to learn the hard way:
1. Anytime you call a Qiime2 command that outputs a directory of files (like qiime diversity core-metrics-phylogenetic), Qiime and Snakemake get mad at each other because Snakemake creates the output directory for Qiime. Qiime will then give you an error about how the output directory already exists (because Snakemake created it first).

Instead, you need to specify every single output file that would be in that directory in the Qiime command itself instead of just the output directory. For example:
   
```snakemake
rule core_metrics_analysis:
    input:
        "tree.qza",
        "tax_filt_actual.qza",
        "metadata.tsv"
    output:
        "bray_curtis_distance_matrix.qza",
        "bray_curtis_emperor.qzv",
        "bray_curtis_pcoa_results.qza",
        "evenness_vector.qza",
        "faith_pd_vector.qza",
        "jaccard_distance_matrix.qza",
        "jaccard_emperor.qzv",
        "jaccard_pcoa_results.qza",
        "observed_features_vector.qza",
        "rarefied_table.qza",
        "shannon_vector.qza",
        "unweighted_unifrac_distance_matrix.qza",
        "unweighted_unifrac_emperor.qzv",
        "unweighted_unifrac_pcoa_results.qza",
        "weighted_unifrac_distance_matrix.qza",
        "weighted_unifrac_emperor.qzv",
        "weighted_unifrac_pcoa_results.qza"
    conda:
        "qiime2-2023.5"
    shell:
        """
        qiime diversity core-metrics-phylogenetic \
            --i-phylogeny tree.qza \
            --i-table tax_filt_actual.qza \
            --p-sampling-depth  10000 \
            --m-metadata-file metadata.tsv \
            --o-rarefied-table rarefied_table.qza \
            --o-faith-pd-vector faith_pd_vector.qza \
            --o-observed-features-vector observed_features_vector.qza \
            --o-shannon-vector shannon_vector.qza \
            --o-evenness-vector evenness_vector.qza \
            --o-unweighted-unifrac-distance-matrix unweighted_unifrac_distance_matrix.qza \
            --o-weighted-unifrac-distance-matrix weighted_unifrac_distance_matrix.qza \
            --o-jaccard-distance-matrix jaccard_distance_matrix.qza \
            --o-bray-curtis-distance-matrix bray_curtis_distance_matrix.qza \
            --o-unweighted-unifrac-pcoa-results unweighted_unifrac_pcoa_results.qza \
            --o-weighted-unifrac-pcoa-results ./data/core_outputs/weighted_unifrac_pcoa_results.qza \
            --o-jaccard-pcoa-results ./data/core_outputs/jaccard_pcoa_results.qza \
            --o-bray-curtis-pcoa-results bray_curtis_pcoa_results.qza \
            --o-unweighted-unifrac-emperor unweighted_unifrac_emperor.qzv \
            --o-weighted-unifrac-emperor weighted_unifrac_emperor.qzv \
            --o-jaccard-emperor jaccard_emperor.qzv \
            --o-bray-curtis-emperor bray_curtis_emperor.qzv
        """
```

2. 